### ISSUE TITLE
Permission issue in Docker image

### ISSUE THREAD

**Issue by micudaj** [viadee/camunda-kafka-polling-client#30]
When running from Docker image there is a permission problem that it cannot write last polled timestamp properties files for runtime and repository, as it is trying to write them to root folder as appuser and does not have permissions for it.

**Example stacktrace:**

java.lang.RuntimeException: Error writing last polled timestamp to ./lastPolled-runtime.properties
at de.viadee.camunda.kafka.pollingclient.service.lastpolled.filebased.FilebasedLastPolledServiceImpl.updatePollingTimeslice(FilebasedLastPolledServiceImpl.java:106) ~[classes!/:na]
at de.viadee.camunda.kafka.pollingclient.job.runtime.RuntimeDataPollingService.run(RuntimeDataPollingService.java:67) ~[classes!/:na]
at de.viadee.camunda.kafka.pollingclient.job.runtime.RuntimeDataPollingJob.executeScheduled(RuntimeDataPollingJob.java:29) ~[classes!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.io.FileNotFoundException: ./lastPolled-runtime.properties (Permission denied)
at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_181]
at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_181]
at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_181]
at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_181]
at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:178) ~[commons-io-1.3.2.jar!/:1.3.2]
at de.viadee.camunda.kafka.pollingclient.service.lastpolled.filebased.FilebasedLastPolledServiceImpl.updatePollingTimeslice(FilebasedLastPolledServiceImpl.java:103) ~[classes!/:na]

**Comment by MTwelkemeier** [comment]
@micudaj Can you check, if the modified image structure (as provided with branch `feature/30_Permission_issue_in_docker_image`) is working for you?
